apiVersion: v2
name: thaliumx
description: ThaliumX Trading Platform Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - trading
  - fintech
  - blockchain
  - cryptocurrency
maintainers:
  - name: ThaliumX Team
    email: devops@thaliumx.com
dependencies:
  - name: postgresql
    version: "13.2.24"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "18.6.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: kafka
    version: "26.6.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled
  - name: keycloak
    version: "18.3.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: keycloak.enabled